server:
  port: 8800

spring:
  application:
    name: configserver
  cloud:
    config:
      server:
        git:
          uri: git@github.com:Leeforrest/learn-git.git
security:
                    basic:
                      enabled: false